### ISSUE TITLE
Add maintainers to Listing

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/marketplace-rest-api#28]
See https://github.com/EclipseFdn/marketplace-rest-api-specs/issues/27

**Comment by chrisguindon** [comment]
Please see:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551901

it was decided that the API should return information about the organization and the author. MPC will display the organization  and if that information is missing, they will print the authors name.

**Comment by autumnfound** [comment]
This has been completed
