### ISSUE TITLE
Do not include secrets in the Docker image

### ISSUE THREAD

**Issue by mbarbero** [EclipseFdn/marketplace-rest-api#71]
Please remove lines https://github.com/EclipseFdn/marketplace-rest-api/blob/master/src/main/docker/Dockerfile.jvm#L19-L27 

Whatever you use to test the container, you will need to update it to inject a volume.

Also remove  -Dconfig.secret.path=${SECRET_LOCATION}/secret.properties from the ENV JAVA_OPTIONS. I'd suggest we leave this as soemthing to be passed when starting the container, e.g.

docker run -it --rm -v ~/production/secrets/marketplace-rest-api:/run/secrets eclispefdn/marketplace-rest-api -Dconfig.secret.path=/run/secrets/very.secret.properties

(or use docker compose secret)

Once you made it work with the docker container on your laptop, I can update the k8s deployment files to make use of kube secrets.

**Comment by autumnfound** [comment]
Managed to run using the following command: 
`docker run -i --rm -p 8090:8090 -v <full path to secret file folder>:/run/secrets --env config.secret.path=/run/secrets/secret.properties quarkus/mpc-rest-api-jvm`

Only needed a small tweak in the secret config loader. That work for you?

**Comment by mbarbero** [comment]
Yes, works for me. Thanks!

**Comment by autumnfound** [comment]
This has been solved, and the changes have been merged in
